version: '3.8'

services:
  # backend service
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    command: npm run dev
  
  # frontend-admin service
  frontend-admin:
    build: ./frontend-admin
    volumes:
      - ./frontend-admin:/app
    ports:
      - "80:5173"
    command: npm run dev

  # database
  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: order_app
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./backend/database/db_data:/var/lib/mysql

  # database view
  prisma-studio:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - backend
    ports:
      - "5555:5555"
    command: npx prisma studio
  
  # # api document
  # swagger-ui:
  #   image: swaggerapi/swagger-ui
  #   container_name: "swagger-ui"
  #   ports:
  #     - "8002:8080"
  #   volumes:
  #     - ./backend/api:/openapi
  #   environment:
  #     SWAGGER_JSON: /openapi/openapi.yaml