version: '3.8'

services:
  backend:
    image: node:21-alpine
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    command: npm start